name = "my_computer"
version = "0.1.0"
licences = ["Apache-2.0"]
description = "A Gleam project"

repository = { type = "github", user = "lpil", repo = "my-computer" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[javascript]
runtime = "deno"

[javascript.deno]
allow_read = [
  "gleam.toml",
  "test",
  "build",
  "tmp",
]
allow_write = [
  "tmp",
]

[dependencies]
gleam_stdlib = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 0.7"
